language: android
jdk:
  - oraclejdk8
sudo: false
env:
   global:
     - GRADLE_OPTS="-Xms2048m"
     - ANDROID_API_LEVEL=26
     - ANDROID_BUILD_TOOLS_VERSION=26.0.2
     - ANDROID_ABI=armeabi-v7a
android:
    components:
      - tools
      - platform-tools
      - tools
      - build-tools-26.0.2
      - android-26
      - extra-android-m2repository
      - extra-android-support
      - extra-google-m2repository
      - sys-img-armeabi-v7a-android-26.0.2
before_script:
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
before_install:
    - chmod +x gradlew
    - echo yes | android update sdk --no-ui --force --all --filter platform-tools > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter android-26 > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter sysimg-18 > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter extra-android-support > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter extra-android-m2repository > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter build-tools-26.0.2 > /dev/null

script:
  - ./gradlew clean build --stacktrace
