language: android
jdk:
  - oraclejdk8
sudo: false
env:
  matrix:
    - TEST=unit
    - TEST=android ANDROID_TARGET=android-26 ANDROID_ABI=google_apis/armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=10
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
  components:
    - build-tools-26.0.2
    - android-26
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - extra

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - android list targets
  - ./gradlew clean
  - ./create_svd.sh

before_install:
  - chmod +x gradlew
  - chmod +x create_svd.sh
  - chmod +x build.sh
  - echo yes | android update sdk --no-ui --force --all --filter platform-tools > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter android-26 > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter sysimg-18 > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter extra-android-support > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter extra-android-m2repository > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter build-tools-26.0.2 > /dev/null

script:
  - ./build.sh
