language: android
jdk:
  - oraclejdk8
sudo: false
env:
   global:
     - GRADLE_OPTS="-Xms2048m"
android:
    components:
      - tools
      - build-tools-25.0.2
      - android-23
      - extra-android-m2repository
      - extra-android-support
      - extra-google-m2repository
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
before_install:
    - chmod +x gradlew
    - echo yes | android update sdk --filter platform-tools --no-ui --force --all > /dev/null
    - echo yes | android update sdk --filter android-19 --no-ui --force --all > /dev/null
    - echo yes | android update sdk --filter sysimg-18 --no-ui --force --all > /dev/null
    - echo yes | android update sdk --filter extra-android-support --no-ui --force --all > /dev/null
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force --all > /dev/null
    - echo yes | android update sdk --filter build-tools-25.0.2 --no-ui --force --all > /dev/null

script:
  - ./gradlew clean build --stacktrace
