language: android
jdk:
  - oraclejdk8
sudo: false
env:
  matrix:
    - TEST=unit
    - TEST=android ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - TEST=android ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    - TEST=android ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=10
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
    components:
    - tools
    - platform-tools
    - tools
    # looking for update
    - build-tools-25.0.2
    - build-tools-24.0.1
    - build-tools-23.0.2
    - android-22
    - android-23
    - android-24
    - android-25
    - extra-android-m2repository
    - extra
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22

before_script:
  - android list targets
  - ./gradlew clean
  - ./create_avd.sh


before_install:
  - chmod +x gradlew
  - echo yes | android update sdk --no-ui --force --all --filter platform-tools > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter android-24 > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter sysimg-18 > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter extra-android-support > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter extra-android-m2repository > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter build-tools-24.0.1 > /dev/null

script:
  - ./build.sh
