language: android
jdk:
  - oraclejdk8
sudo: false
env:
  matrix:
    - TEST=unit
    - TEST=android ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=10
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
    components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra
    - sys-img-armeabi-v7a-android-25

before_script:
  - android list targets
  - ./gradlew clean
  - ./create_svd.sh

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - chmod +x create_svd.sh
  - chmod +x build.sh
  - echo yes | android update sdk --no-ui --force --all --filter platform-tools > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter android-25 > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter sysimg-18 > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter extra-android-support > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter extra-android-m2repository > /dev/null
  - echo yes | android update sdk --no-ui --force --all --filter build-tools-25.0.2 > /dev/null

script:
  - ./build.sh
