language: android
jdk:
  - oraclejdk8
sudo: false
env:
   global:
     - GRADLE_OPTS="-Xms2048m"
android:
    components:
      - tools
      - build-tools-25.0.1
      - android-24
      - extra-android-m2repository
      - extra-android-support
      - extra-google-m2repository
before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
before_install:
    - chmod +x gradlew
    - echo yes | android update sdk --no-ui --force --all --filter platform-tools > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter android-24 > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter sysimg-18 > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter extra-android-support > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter extra-android-m2repository > /dev/null
    - echo yes | android update sdk --no-ui --force --all --filter build-tools-25.0.1 > /dev/null

script:
  - ./gradlew clean build --stacktrace
